# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  build-2secure: appdome/build-2secure@1.0.1
  orb-tools: circleci/orb-tools@11.5

executors:
  my-executor:
    docker: 
     - image: cimg/python:3.11.3
    working_directory: /tmp

jobs:
  downstream:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp
      - run:
          name: "ls_run"
          command: |
            sudo ls /tmp
            sudo ls /tmp/appdome-output

workflows:
  btd:
    jobs:
      - build-2secure/appdome_runner:
          name: "test-android-autodev-private-sign"
          runner: "ANDROID_AUTO_DEV_SIGNING"
          team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
          appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/AndroidMediaPlayer.apk"
          output: "appname.apk"
          post-steps: # steps to run after steps defined in the job bar
            - persist_to_workspace:
                root: /tmp
                paths:
                  - appdome-output
      - downstream:
          requires:
            - test-android-autodev-private-sign

