version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Your build steps here

      # Store the desired artifact in the artifacts folder
      - run:
          name: Save artifact
          command: |
            # Generate or retrieve the app_link.apk artifact
            # For example:
            echo "Sample app_link.apk content" > app_link.apk
            mkdir -p $CIRCLE_ARTIFACTS
            mv app_link.apk $CIRCLE_ARTIFACTS/

  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Retrieve the artifact from the artifacts folder
      - run:
          name: Retrieve artifact
          command: |
            # Access the app_link.apk artifact
            cp $CIRCLE_ARTIFACTS/app_link.apk .

      # Use the artifact in the deployment step
      - run:
          name: Deploy app
          command: |
            # Perform your deployment using the app_link.apk file
            # For example:
            ./deploy_script.sh app_link.apk

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
